# Generated by Django 2.1.4 on 2018-12-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181218_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='dbuser',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('dbuser', 'dbhost')},
        ),
    ]
