# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=150, null=True, unique=True)),
                ('password', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('path', models.FilePathField(blank=True, default='', max_length=255, null=True)),
                ('status', models.BooleanField(default='1')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
    ]
